syntax = "proto3";

package admin.core.v1;

import "google/api/annotations.proto";

import "common/pagination/v1/pagination.proto";

import "core/audit/v1/data_access_audit_log.proto";

// 数据访问审计日志管理服务
service DataAccessAuditLogService {
  // 查询数据访问审计日志列表
  rpc List (.common.pagination.v1.PagingRequest) returns (.core.audit.v1.ListDataAccessAuditLogResponse) {
    option (google.api.http) = {
      get: "/admin/v1/data-access-audit-logs"
    };
  }

  // 查询数据访问审计日志详情
  rpc Get (.core.audit.v1.GetDataAccessAuditLogRequest) returns (.core.audit.v1.DataAccessAuditLog) {
    option (google.api.http) = {
      get: "/admin/v1/data-access-audit-logs/{id}"
    };
  }
}
