syntax = "proto3";

package core.permission.v1;

import "gnostic/openapi/v3/annotations.proto";

import "google/api/annotations.proto";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/field_mask.proto";

import "common/pagination/v1/pagination.proto";

// 权限点 - 菜单 关联关系
message PermissionMenu {
  // ID。
  optional uint32 id = 1 [
    (gnostic.openapi.v3.property) = { description: "ID" }
  ]; // ID

  // 权限点ID。
  optional uint32 permission_id = 2 [
    (gnostic.openapi.v3.property) = { description: "权限点ID" }
  ]; // 权限点ID

  // 菜单ID。
  optional uint32 menu_id = 3 [
    (gnostic.openapi.v3.property) = { description: "菜单ID" }
  ]; // 菜单ID
}
